name: hisab

services:
  postgres:
    image: postgres:16-alpine
    container_name: hisab-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-hisab_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hisab_password}
      POSTGRES_DB: ${POSTGRES_DB:-hisab_dev}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: hisab-redis
    restart: always
    ports:
      - "6379:6379"

  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: hisab-seaweedfs
    restart: always
    ports:
      - "8333:8333"
      - "9333:9333"
    command: "server -s3"

volumes:
  postgres_data:
